# Generated by Django 5.0.4 on 2024-04-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnaproject',
            name='associated_application_link',
        ),
        migrations.AddField(
            model_name='tnaproject',
            name='associated_application_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_project', to='tna.tnaproject'),
        ),
    ]
