# Generated by Django 5.0.4 on 2024-04-22 22:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0003_tnaproject_additional_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tnaproject',
            name='additional_participants',
        ),
        migrations.AddField(
            model_name='tnaproject',
            name='additional_participants',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
