# Generated by Django 5.0.4 on 2024-04-24 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0006_tnaproject_additional_participants'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnaproject',
            name='additional_participants',
            field=models.ManyToManyField(blank=True, default='', null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='approach',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='associated_application',
            field=models.CharField(blank=True, choices=[('yes', 'Yes'), ('no', 'No')], default=''),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='associated_application_title',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='associated_project', to='tna.tnaproject'),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='context',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='impact',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='objective',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='principal_investigator',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tna_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='project_title',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='research_installation_1',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='research_installation_2',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='research_installation_3',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='scientific_question_hypothesis',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='state_art',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
        migrations.AlterField(
            model_name='tnaproject',
            name='strategy',
            field=models.CharField(blank=True, default='', max_length=2000),
        ),
    ]
