# Generated by Django 5.0.4 on 2024-05-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0008_tnaproject_tna_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='tnaproject',
            name='record_status',
            field=models.CharField(blank=True, choices=[('saved', 'saved'), ('submitted', 'submitted')], default=''),
        ),
    ]
