# Generated by Django 5.0.4 on 2024-04-22 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tna', '0005_remove_tnaproject_additional_participants'),
        ('users', '0002_user_organization_address_user_organization_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tna_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_participants', to='tna.tnaproject'),
        ),
    ]
