# Generated by Django 5.0.4 on 2024-04-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_organization_address_user_organization_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnaproject',
            name='another_application',
            field=models.CharField(choices=[('yes', 'Yes'), ('no', 'No')]),
        ),
    ]
