# Generated by Django 5.0.4 on 2024-04-18 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_tnaproject_another_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tnaproject',
            name='another_application_link',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.tnaproject'),
        ),
    ]
